### ISSUE TITLE
Paquets manquants 

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Tuto-Arch#1]
Paquets AUR utiles manquants :

Rebuild-detector
Reflector-simple

Pour AMD : 

amd-vulkan-prefixes (je dois vérifier si encore obligatoire/soucis de perfs)

**Comment by Cardiacman13** [comment]
On va faire ça, quand je rentre du boulot je te donne accès au git dav.

**Comment by Cardiacman13** [comment]
Yep ce soir l'infiltré audite le code et il valide. On va ajouter la lib32 de pipewire au passage !
