### ISSUE TITLE
Fish pas par défaut après le script de post-install

### ISSUE THREAD

**Issue by T13nou** [Cardiacman13/Tuto-Arch#10]
Fish est installé à l'issue du script mais ne s'execute pas automatiquement lors de l'ouverture d'une nouvelle Konsole

**Comment by Cardiacman13** [comment]
J'ai eu ça aussi, pourtant après la commande ```chsh -s /usr/bin/fish``` il me demande bien le mdp. Tu as eu la demande du mdp aussi ?

**Comment by cfrancie** [comment]
Il est nécessaire de procéder à un redémarrage système pour que la commande `chsh -s /usr/bin/fish` (qui sert à mettre fish en shell par défaut) prenne effet.

**Comment by Xdavius** [comment]
Chez moi tout est passé mais j'ai pas pas eu fish au reboot (enfin je crois) juste l'erreur man a l'installation pourtant.
Pas testé plus.

**Comment by Cardiacman13** [comment]
Je viens de faire un test en vm sur une arch propre et ça marche chez moi. Et je ne vois pas d'erreur à par l'erreur man mais qui normalement n'est pas bloquante. Il y a bien marqué que l'interpréteur à été modifié et je l'ai bien au reboot. 
![Screenshot_20230920_235035](https://github.com/Cardiacman13/Tuto-Arch/assets/83916775/2c9b5e20-2089-4e54-853f-b4ce14b05c60)

**Comment by Xdavius** [comment]
Ok manque juste man en paquet obligatoires pour résoudre manpath

**Comment by cfrancie** [comment]
Il est vrai que j'envisage de l'ajouter, car cela serait utile pour les utilisateurs intermédiaires.

**Comment by Cardiacman13** [comment]
![Screenshot_20230921_092229](https://github.com/Cardiacman13/Tuto-Arch/assets/83916775/98f1a22b-5e05-4e4e-800b-0e6cc9fbd39b)
Je viens de re tester ce matin et ça a fonctionné encore.. Si vous pouvez refaire un test pour confirmer ?

**Comment by T13nou** [comment]
Je rajoute que le constat d'hier n'était pas sur une VM mais une installation en dur. Selon le temps dispo je rejouerai le scénario

**Comment by Cardiacman13** [comment]
Je viens de refaire une dizaine de tests (marseillais donc ou 4 ou 5) et ça marche à voir si vous pouvez répéter.  Attention de bien être à jour et de supprimer le dossier histoire d'être sûr.
