### ISSUE TITLE
Timeshift non installé

### ISSUE THREAD

**Issue by T13nou** [Cardiacman13/Tuto-Arch#11]
Timeshift n'est pas installé à l'issue du script

En décallage avec le tuto

**Comment by Xdavius** [comment]
+1

En fonction de btrfs ou non, il faut installer snapper/timeshift ?
Je sais pas comment ça fonctionne pour systemd-boot par contre.

**Comment by Cardiacman13** [comment]
Oui je d'accord, pour btrfs-assistant

**Comment by Cardiacman13** [comment]
6f01875 Corrigé

**Comment by Cardiacman13** [comment]
6f01875
