### ISSUE TITLE
Lutris non installé

### ISSUE THREAD

**Issue by T13nou** [Cardiacman13/Tuto-Arch#12]
Lutris n'apparait pas suite à l'éxecution du script

**Comment by tobal37** [comment]
idem chez moi

**Comment by Xdavius** [comment]
Idem. Ni Lutris ni Steam. J'ai eu juste Kdenlive. J'ai pris sans flatpak.

(Je comprends toujours pas le choix de flatpak sur Arch mais bon 😂 je suis un vieux con. Bientôt 40 ans c'est foutu pour moi 🤣)

**Comment by Cardiacman13** [comment]
Corrigé ca68732
