### ISSUE TITLE
GamePad 

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Tuto-Arch#15]
Ajouter bluez-plugins pour le support des manettes PS3 en wifi

Ajouter support manette PS4/PS5 ? (A vérifier la méthode, quelqu'un pour tester ???(

**Comment by Cardiacman13** [comment]
bluez-plugins y est déjà ligne 137; il ne s'installe pas ?

**Comment by Xdavius** [comment]
Ah oui exact 😜

Faudra juste voir pour manette PS4/5

J'ai pas de matos pour tester par contre 😔

**Comment by Cardiacman13** [comment]
Ça c'est un paquet à compiler et même avec un R9 c'est un peu long donc je ne suis pas fan d'ajouter "ds4drv". L'autre paquet était bien là. À voir qi il y a une autre solution pour le moment... Je ne mets pas ça dans le script.
