### ISSUE TITLE
Check pour btrfs assistant 

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Tuto-Arch#16]
J'ai repris ta ligne de check pour mkinitcpio.conf.

Elle permet de vérifier la présence de btrfs pour proposer btrfs assistant :

if [[ $(cat /etc/mkinitcpio.conf | grep -c "MODULES=(btrfs") -eq 1 ]]; then

**Comment by Cardiacman13** [comment]
Ça c'est une bonne idée MERCI Dav. Ça fera une question de moins et normalement les gars qui veulent btrfs veulent btrfs-assistant.

**Comment by cfrancie** [comment]
Fix dans [aaab86d](https://github.com/Cardiacman13/Tuto-Arch/commit/740cbfbb498c9a3c79c6c9a7615848c787c58254) Merci :)
