### ISSUE TITLE
ajouter mesa-vulkan-layers & lib32-mesa-vulkan-layers

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Tuto-Arch#18]
***After the merge request was open for more than a half-year, Mesa 20.1 has landed a Vulkan device selection layer for choosing between multiple Vulkan-enabled GPUs on a given system as the default device.

This Vulkan layer allows for picking the default GPU for X11/Wayland/device sessions, similar to DRI PRIME for OpenGL. This Vulkan layer first checks for the MESA_VK_DEVICE_SELECT= environment variable for being pointed towards the GPU/driver to be used, otherwise checks DRI_PRIME and tries to match it to a proper configuration.***

Ce paquet est utiles dans les config PC portable AMD/AMD et INTEL/AMD

A ajouter dans les paquets GPU intel et nvidia

Ne genèrent pas de conflit.

**Comment by Cardiacman13** [comment]
J'ai un peu peur j'aimerai des tests, je dis ça car je ne savais pas que ce paquet existe et que ça à toujours fonctionné sans en avoir besoin. Du coup vu que ça fonctionne sans... Je suis plus d'avis que si ça marche sans on ne touche pas. J'aimerai un cas concret d'utilisation ou sans ça marche pas et avec ça marche.

**Comment by Xdavius** [comment]
Le problème c'est que ça ne concerne que les laptop compatible Mesa... Du coup c'est le fichier qui est ajouté par défaut sur TW (le laptop Alienware full AMD, c'est ça qui le fait fonctionner)

D'ailleurs je suis en recherche sur les autres distributions (c'est ce qui permet le DRI_PRIME=1) et c'est sûrement a cause de ça qui est manquant partout par défaut que le type s'est est cassé les dents.

**Comment by Xdavius** [comment]
Au fait, ce paquet normalement permet aussi d'utiliser une CG AMD avec l'IGPU activé pour les 5600G et R7000.

C'est ce qui permet de résoudre l'issue que l'on a eu il y a quelques temps sur le help me sur PC fixe !

Par contre, à ce jour, tant que l'on n'aura pas testé exactement comment ça fonctionne..

Laisse cette issue ouverte, on verra dans le futur

**Comment by Cardiacman13** [comment]
Oui on va faire ça il nous faudrait un cobaye mais les laptop AMD Gaming ça ne court pas les rues. Peut être demander à celui que l'on avait aidé si il a le temps de faire des tests.

**Comment by Xdavius** [comment]
Je UP ce paquet.
Il est installé par défaut sur Debian, Opensuse et Ubuntu. 3 Distributions où on a aucun problèmes pour le jeux vidéo globalement. D'ailleurs c'est le seul ICD activé dans implicit_layer.d
![Screenshot_20230929_123209](https://github.com/Cardiacman13/Tuto-Arch/assets/66792063/cbb85811-fb9c-4785-abee-a89301188c8a)

**Comment by Cardiacman13** [comment]
OK fais une pull request, je valide en rentrant

**Comment by Cardiacman13** [comment]
fait https://github.com/Cardiacman13/Tuto-Arch/commit/764d9f04051c6aaa34c57aaae01d70ef210afe9a
