### ISSUE TITLE
Script Post_Install - Faute de frappe

### ISSUE THREAD

**Issue by ChristophePI6060** [Cardiacman13/Tuto-Arch#24]
Hello, 
J'ai remarqué une faute au moment de la question de l'imprimante HP:
Il est marqué imprimente :)

![Screenshot_20230921_222958](https://github.com/Cardiacman13/Tuto-Arch/assets/71064143/93f46687-4184-4567-a47e-1236953c4618)

Voila
Belle journée ;)

**Comment by Cardiacman13** [comment]
Fait ! a8dafc8, Merci du retour.

**Comment by Cardiacman13** [comment]
Fait ! https://github.com/Cardiacman13/Tuto-Arch/commit/a8dafc87add7129f7614be291de1e290b8c76661, Merci du retour.
