### ISSUE TITLE
Ajouter vérification pour multilib

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Tuto-Arch#26]
Pour les installations Custom sans passer par archinstall (qui fait chier pour la /boot de 512m, que je trouve insuffisante), ce serait bien d'ajouter un check pour multilib si il est bien activé. 

Cela permet aussi d'éviter des problèmes pour veux qui l'oublient dans archinstall

**Comment by Cardiacman13** [comment]
Oui très bonne idée ! On va faire ça.

**Comment by wmemcpy** [comment]
C'est fix merci bcp 1
