### ISSUE TITLE
Paquet KDE inutile

### ISSUE THREAD

**Issue by rficasa** [Cardiacman13/Tuto-Arch#28]
Je suis sur GNOME, j'ai donc pris l'install post-installation sans le KDE derrière.
Le script m'a quand même installé tous les composants QT6 et j'ai vu passé des plasma-session dans le lot des paquets installés alors qu'ils me sont parfaitement inutile avec ma DE.

**Comment by Cardiacman13** [comment]
Merci pour l'issue ! Normalement c'est corrigé dans dd93cf9 :)
