### ISSUE TITLE
pb avec install pipewire

### ISSUE THREAD

**Issue by LordSvein** [Cardiacman13/Tuto-Arch#32]
error: target not found: pulseaudio
warning: pipewire-1:0.3.80-1 is up to date -- skipping
error: target not found: lib32-pipewire
Erreur lors de l'exécution de la commande : sudo pacman -S --needed --noconfirm pipewire lib32-pipewire pipewire-pulse pipewire-alsa pipewire-jack wireplumber
[lordsvein@wolfgaming Tuto-Arch]$ ^C

**Comment by Cardiacman13** [comment]
On a oublié de forcer les Lib32 et tu a oublié de cocher le multilib dans archinstall. Dans la prochaine version qui arrive bientôt  on force le multilib pour ceux qui oublient.

**Comment by Cardiacman13** [comment]
Workaround en attendant le fix : ```sudo nano  /etc/pacman.conf
``` décommenter : ```[multilib]``` et 
```Include = /etc/pacman.d/mirrorlist``` puis ```pacman -Syy``` et relancer le script.

**Comment by Cardiacman13** [comment]
Cf https://github.com/Cardiacman13/Tuto-Arch/issues/26
