### ISSUE TITLE
Ajouter la Précision XPADNEO pour les manettes

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Tuto-Arch#37]
La question n'est pas claire. Il faut préciser "xpadneo pour manettes Xbox Series X|S"
 
proposer [xone-dkms-git](https://aur.archlinux.org/packages/xone-dkms-git/) + [xone-dongle-firmware](https://aur.archlinux.org/packages/xone-dongle-firmware/) pour manettes xbox avec dongle ?

proposer support manettes switch [hid-nintendo-dkms](https://aur.archlinux.org/packages/hid-nintendo-dkms/) ?
proposer [dualsensectl-git](https://aur.archlinux.org/packages/dualsensectl-git/) pour manettes PS5 ?

Je pense que PS5 + Switch se serait bien. Pour le dongle, a voir (ça concerne beaucoup de monde ?)

**Comment by Cardiacman13** [comment]
Quand je lis ça j'ai même envie d'enlever xpadneo. On peut pas tout couvrir il y a déjà beaucoup de questions (trop à mon gout) du coup je ne me sens pas de rajouter une question par manette. Et Xpadneo ça gère plus que les manettes Xbox Series X|S

**Comment by Cardiacman13** [comment]
3284b61

**Comment by Xdavius** [comment]
```Et Xpadneo ça gère plus que les manettes Xbox Series X|S```

dépend des versions des manettes...
