### ISSUE TITLE
yay trop verbeux

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Tuto-Arch#39]
ajouter un affichage de la liste des paquets et rendre yay muet mais conserver un log ?

echo ${packages}
yay -Sy ${packages} > /tmp/packlog 2>&1

**Comment by Cardiacman13** [comment]
Bon la pour le coup on voit plus rien :
![image](https://github.com/Cardiacman13/Tuto-Arch/assets/83916775/2f6016f8-2f9a-4e86-8aae-6fcbeac82046)
