### ISSUE TITLE
Correction a la fin du script 

### ISSUE THREAD

**Issue by getsugah** [Cardiacman13/Tuto-Arch#43]
Bonjour, juste pour être plus propre, faudrait voir pour corriger la syntaxe.

`\e[31mLe système redémarre dans 10 secondes ou appuyez sur Ctrl+C pour annuler.\e[0m`

**Comment by wmemcpy** [comment]
Merci c'est fix dans [95680aa](https://github.com/Cardiacman13/Tuto-Arch/commit/95680aab8171d826a6b7dea306c1bb4e2871b44d)
