### ISSUE TITLE
Configuration MKINITCPIO vconsole font

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Tuto-Arch#44]
les hooks keymap et consolefont dans mkinitcpio.conf se configurent dans vconsole.conf.

il faudrait pousser la configuration de /etc/vconsole.conf en écrastant la conf :

LOCALE="fr_FR.UTF-8"
KEYMAP="fr"
USECOLOR="yes"

il faut désactiver consolefont dans le HOOK de mkinitcipo.conf

HOOKS=(base udev autodetect modconf kms keyboard keymap block filesystems fsck)

J'ai un bug et erreur avec consolefont. si vous avez une solution (avec TKG en tout cas)...

Cette conf passe bien.

LOCALE ne semble pas obligatoire.

**Comment by Cardiacman13** [comment]
Mmm tu parles sur ton système ? Car avec un système installé avec archinstall c'est bien fait et on a pas ce problème.

**Comment by Xdavius** [comment]
> Mmm tu parles sur ton système ? Car avec un système installé avec archinstall c'est bien fait et on a pas ce problème.

Mon système mais peu importe

L'ajout de color permet d'ajouter la couleur au terminal TTY 

Supprimer consolefont dans initramfs permet de sauter les erreurs de confs de consolefont.

Et ça sert pas à grand chose.

Ajouter locale a vconsole c'est bien pratique aussi.

Ça reste une conf standard de arch. Je pense qu'il faut la pousser simplement.

C'est une amélioration de confort.

**Comment by Cardiacman13** [comment]
Vu avec dav je close
