### ISSUE TITLE
Carte graphique : Détecter Virtualbox / Vmware

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Tuto-Arch#45]
Ajouter la detection auto pour les VM (ouaiiiiii ca ce serait génial :p)

**Comment by Cardiacman13** [comment]
Ce n'est pas vraiment le but "Le but de ce tuto et de ce script est d’installer une Arch stock avec un minimum de paquet, selon nos besoins. " et finalement on a supprimé la détection auto.
