### ISSUE TITLE
Manque informations pour UFW

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Tuto-Arch#5]
Ufw est installé sans consentement ni informations, et activé par défaut.

Cela peut bloquer les utilisateurs souhaitant utiliser Samba dans le futur

Suggestion : ajouter une question "Souhaitez vous installer et activer le pare-feu UFW ?"

**Comment by Cardiacman13** [comment]
Oui c'est clairement un oubli, on corrige ça de suite.

**Comment by Cardiacman13** [comment]
Fait !

**Comment by Cardiacman13** [comment]
On a décidé de le forcer. Les gars qui utilisent samba doivent savoir ça.

**Comment by Xdavius** [comment]
????
Aucun rapport le firewall. Par contre faut ouvrir les ports a chaque fois que tu dois avoir accès à un service même local.

Forcer UFW, c'est pas KISS.
