### ISSUE TITLE
Bash-completion et bluetooth 

### ISSUE THREAD

**Issue by opentux** [Cardiacman13/Tuto-Arch#59]
Salut.

Alors me concernant quand j'ai testé l'installation. Le bluetooth ne s'active pas. Alors que je crois bien avoir vu sa présence dans les scripts. (Sa s'active bien après coup)

Dans le cas où on installe pas fish il n'y a pas le bash-completion d'installé... (Perso c'est le minimum syndical pour moi)

Après j'utilise zsh avec le thème manjaro-zsh-config... que j'aime beaucoup mais je m'égare.

Sinon pour KDE moi j'utilise kwalletmanager pour gérer son trousseau de clé et aussi le yakuake pour avoir la console KDE a la mode quake. (C'est juste une idée comme une autre je ne sais pas si d'autres, utilise ça.)

Un dernier pour la route si tu rajoutes packagekit-qt5, discover est capable d'installer et d'update du package Pacman...( après reboot mais ne concerne pas "aur "donc bon c'est qu'une idée en passant)

Je ferai sûrement des petits ajouts de mon côté dans un fork pour mon utilisation perso ( mais sinon merci pour cette série de script... )

Si jamais j'ai des idées je posterai du merge request plutôt, pour ne pas polluer :)

**Comment by Cardiacman13** [comment]
Salut, merci pour le retour :) 

- bash-completion normalement il est forcé pour tout le monde il est dans packages.sh ligne 37.
- Pour le Bluetooth on va investiguer
- Pour packagekit-qt5 il me semble que Arch déconseille d'utiliser autre chose que pacman. D'ailleurs je me demande si une update par discover avec packagekit lance les pacman hooh ? 
- Pour le reste oui faut fork avec tes choix perso ici le but c'est de suivre le tuto :)

**Comment by Cardiacman13** [comment]
Pour le bluetooth je ne suis pas sûr d'avoir compris, ça s'active après coup c'est à dire ? C'est toi qui l'a activé ou ça s'active au reboot ?

**Comment by opentux** [comment]
Ha j'ai le doute la. Pour moi le bluetooth n'est pas activé du tout... mais je me rappelle plus de l'état au reboot... et oui c'est moi qui active le service après coup.

**Comment by tobal37** [comment]
j ai pas de bluetooth sur gnome

**Comment by Cardiacman13** [comment]
Ok je pense que on va laisser tomber l'auto détection et juste poser la question : "voulez vous activer le bluetooth"

**Comment by Cardiacman13** [comment]
Je pense que on a fix : https://github.com/Cardiacman13/Tuto-Arch/compare/v1.0.1...v1.0.2
Si vous avez le temps de regarder c'est cool :)

**Comment by tobal37** [comment]
C est fix sur gnome

**Comment by opentux** [comment]
c'est bon aussi sur kde le service bluetooth s'active bien
