### ISSUE TITLE
Bugs divers

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Tuto-Arch#6]
- Pour l'arrivée des questions, il faut une mise en page(la question est noyé après pacman
- ajouter un reflector en début de script (allemage et france, ce sont les best)
- auto détection BTRFS/EXT4
- ajouter 'man' aux paquets obligatoires (erreur fish need man)
- Manque imprimantes : hplip ou ajouts aussi canon/epson ? 
- Renomer le titre logiciels de base -> logiciels divers
- Aerer un peu le text (ca fait trop pavé, ajouter des espaces)
- j'ai mis non au flatpak mais j'ai pas lutris ni steam (kdenlive est passé)

- Ajouter une option par défaut pour y/n lors des chois (ecrit Y majuscule pour le oui par défaut, ajouter la couleur vert/rouge y=vert n=no)

**Comment by Cardiacman13** [comment]
OK on va faire ça, juste le coup de Reflector si on est canadien par
exemple  ce n'est pas fou les serveurs France, Allemagne.

**Comment by cfrancie** [comment]
Tu peux nous donner le SHA du commit sur lequel tu as eu ce problème de Flatpak ?

**Comment by Xdavius** [comment]
> OK on va faire ça, juste le coup de Reflector si on est canadien par exemple ce n'est pas fou les serveurs France, Allemagne. Le mer. 20 sept. 2023, 14:28, Davius ***@***.***> a écrit :


C'est pas faux 🤣
