### ISSUE TITLE
Activation bluetooth

### ISSUE THREAD

**Issue by leboural** [Cardiacman13/Tuto-Arch#71]
![image](https://github.com/Cardiacman13/Tuto-Arch/assets/60667964/b5b8ebfc-199f-434b-becd-e7f2b2df9282)

**Comment by Cardiacman13** [comment]
Merci je corrige, en attendant pour ne pas tout refaire tu peux simplement faire 
```yay -S --needed bluez bluez-utils bluez-plugins && sudo systemctl enable --now  bluetooth.service```

**Comment by Cardiacman13** [comment]
fix 7cf97bd

**Comment by leboural** [comment]
Oui merci
