### ISSUE TITLE
Gestion de la langue

### ISSUE THREAD

**Issue by leboural** [Cardiacman13/Tuto-Arch#72]
je galere a tout mettre en francais. l installe de base ne me permet pas de faire un loadkeys fr 
J ai du faire :
localectl list-keymaps
localectl set-x11-keymap fr
localectl set-locale LANG=fr_FR
modifier le /etc/locale.conf et faire un locale-gen

Et meme comme ca j ai encore le terminal en anglais
l automatiser serait top
Peut etre y a t il une maniere plus simple

**Comment by Cardiacman13** [comment]
Nop on peut pas le forcer car il y a des Belges des Canadiens ou même des Français qui utilisent un clavier QUERTY qui utilisent le script. En plus arch-install le fait très bien tu as juste du te louper. Perso après arch install je n'ai rien à faire tout est en Français et on est des 10ene à l'utiliser régulièrement tu es le premier à remonter ça. Je suis sûr que tu as fais une erreur.

**Comment by Cardiacman13** [comment]
Tu trouveras la solution ici : https://wiki.archlinux.org/title/Locale 

Perso je ne peux pas t'en dire plus je n'ai jamais eu le problème donc je n'ai pas l'habitude de toucher aux locales.
