### ISSUE TITLE
Proposition d'amélioration sur le choix du GPU

### ISSUE THREAD

**Issue by Temet79** [Cardiacman13/Tuto-Arch#73]
Salut,

Libre à toi de voir si tu préfères ou pas, mais tu peux faire comme ça dans ton script pour le choix du GPU :

```
read -p "Quel est votre GPU? (INTEL/AMD/NVIDIA) : " user_gpu
while [[ ! "INTEL AMD NVIDIA" =~ $user_gpu ]]; do
  read -p "Quel est votre GPU? (INTEL/AMD/NVIDIA) : " user_gpu
done
```
Ça va forcer l'utilisateur à faire un choix valide.

++

David

**Comment by Cardiacman13** [comment]
J'ai testé c'est parfait merci :) 

Fait dans : 6017749

Si tu vois d'autres choses n'hésite.
