### ISSUE TITLE
Timeshift - problème lancement des sauvegardes en automatique 

### ISSUE THREAD

**Issue by Fredbulle** [Cardiacman13/Tuto-Arch#74]
Bonjour, débutant sous linux mais il me semble avoir trouvé une issue sur l'automatisation des sauvegardes timeshift qui ne fonctionne pas sans effectuer les commandes suivantes après l'installation : 

systemctl start cronie 
systemctl start cronie.service 

systemctl enable cronie
systemctl enable cronie.service

**Comment by Cardiacman13** [comment]
![image](https://github.com/Cardiacman13/Tuto-Arch/assets/83916775/2e711820-2905-4f39-88a0-436bccacf45a)
corrigé dans : https://github.com/Cardiacman13/Tuto-Arch/commit/be5b8d0d34151051cce0ef9e5147e70d564416d3
Voilà merci :+1:

**Comment by Fredbulle** [comment]
Ah ok, j'avais déjà passé le script avant sa correction ! Désolé Merci
