### ISSUE TITLE
ntfs-3g n'est plus nécessaire

### ISSUE THREAD

**Issue by hunabku94** [Cardiacman13/Tuto-Arch#75]
ntfs-3g n'est plus nécessaire car il est dans le noyau depuis la release 5.15

**Comment by Cardiacman13** [comment]
On me l'a beaucoup dit car ça se raconte mais c'est faux, ntfs-3g continue d'être meilleur que le module de base ajouté dans le 5.15. Typiquement si tu suis mon tuto sur kde ouvres partition-manager sans le paquet ntfs-3g, tu ne peux même pas formater en ntfs. Ajoute le paquet reboot et hop tu as l'option.

**Comment by Cardiacman13** [comment]
Voilà 2 screens avec et sans le paquet ntfs-3g : 

Avec:
![avec ntfs 3g](https://github.com/Cardiacman13/Tuto-Arch/assets/83916775/6758a453-f26d-49a1-9052-a00870f85405)

Sans : 
![sans ntfs 3g](https://github.com/Cardiacman13/Tuto-Arch/assets/83916775/bcb539ae-a3cf-4d2d-9877-5de8161e2d83)

On voit que je ne peux plus formater, le module ajouté en 5.15 est inférieur au module ntfs-3g.

**Comment by hunabku94** [comment]
merci Cardiacman13
