### ISSUE TITLE
Support manette PS4 pour Bluez

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Tuto-Arch#77]
Le paquet AUR bluez-utils-compat permet le support du bluetooth oldgen pour certains GamePad dont la manette PS4.

Je ne sais pas si c'est intéressant de l'ajouter au script.

**Comment by Cardiacman13** [comment]
Et si je rajoutais une question comme pour xpadneo ? Et ça installerait ds4drv et bluez-utils-compat ?

**Comment by Xdavius** [comment]
Pourquoi pas.
Je sais pas si tu as une section manettes PlayStation.

ps4drv et dualsensectl-git peuvent être ajoutés ensemble dans ce cas-là dans un pack complet pour manette PS4/PS5. Ce sont des drivers userspace. Donc ça craint pas.

La manette PS3 étant déjà géré par bluez-plugins que l'on a déjà intégré.

**Comment by Cardiacman13** [comment]
Je vais faire ça

**Comment by Cardiacman13** [comment]
closed https://github.com/Cardiacman13/Tuto-Arch/commit/91206a2538682bd3cbbee8aeaa39efd8854b7800
