### ISSUE TITLE
Ajout de fonts pour Steam ?

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Tuto-Arch#78]
Vérifier que toutes les ttf importantes sont installés mais je connais pas les paquets essentiels

Installer les fonts Microsoft ?

A contrôler...

**Comment by Cardiacman13** [comment]
C'est ttf-liberation qui se charge pleinement de ça, pas besoin de plus. Par contre je veux biens que tu ouvres une issue en me mettant les paquets que je dois ajouter pour l'option VM.
