### ISSUE TITLE
Carte graphique VM

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Tuto-Arch#79]
Pour vulkan (nécessaire pour Lutris en VM)

Lavapipe: vulkan-swrast lib32-vulkan-swrast

Pour les shaders en mode VM (optionnel mais vraiment génial ce truc)

SwiftShader(AUR): swiftshader-git

Pour les additions te fais pas chier c'est pas obligatoire mais tu peux ajouter une note dans le README pour aider parceque la doc du wiki est pas folle.

**Comment by Cardiacman13** [comment]
Donc tu penses que je mets juste ces 3 paquets :  vulkan-swrast lib32-vulkan-swrast swiftshader-git ?

**Comment by Cardiacman13** [comment]
J'ai push en branche dev  https://github.com/Cardiacman13/Tuto-Arch/commit/6af1c17fda431908b62ce394ca1d6ac9b7047ea1 https://github.com/Cardiacman13/Tuto-Arch/commit/003d1f066649ec97efcaa3f49120cf62c198f6af si tu peux test avant le merge sur main.

**Comment by Xdavius** [comment]
Je test demain

**Comment by Cardiacman13** [comment]
je ferme c'est fait et testé ça fonctionne !
