### ISSUE TITLE
VERNUM

### ISSUE THREAD

**Issue by BerrySwann** [Cardiacman13/Tuto-Arch#84]
Bonjour,

Il n'y aurais pas quelque chose pour activer au demarage le NumVer (Pavé numerique) ?
Si oui, pourrais tu l'ajouter au script ?

merci

**Comment by Cardiacman13** [comment]
Ajout au script : 

Pour **Gnome** : https://github.com/Cardiacman13/Tuto-Arch/commit/88b4a8249bcdb5b371b834fa26179ae89c072d93

Pour **KDE** : https://github.com/Cardiacman13/Tuto-Arch/commit/d5cc61624afa9b7b202ed7cd4d4aea03f7d26398

Pour que tu puisses le faire toi même sans avoir à refaire le script :

Pour **Gnome** : ```gsettings set org.gnome.desktop.peripherals.keyboard numlock-state true```

Pour **KDE** : ```echo "Numlock=on" | sudo tee -a /etc/sddm.conf```

**Sources : https://wiki.archlinux.org/title/Activating_numlock_on_bootup**

Il y a dans ce lien du wiki de Arch les solutions proposées plus haut, ainsi que les différentes solutions pour les autres DE.

**Comment by Cardiacman13** [comment]
Ah oui est merci du retour :) j'ai oublié sorry !
