### ISSUE TITLE
Problème lien vers vidéo Nvidia-All

### ISSUE THREAD

**Issue by Totor954** [Cardiacman13/Tuto-Arch#86]
Le lien 

[Vous utilisez Arch et Nvidia regardez ça !](https://youtu.be/43yYIWMnDJA) pointe vers la vidéo : "Kernel TKG sur Arch + Booster ses perfs"

Voici le bon lien pour modifier : 

https://youtu.be/T0laE8gPtfY

**Comment by Cardiacman13** [comment]
Merci ! :) ed66be4
